
package com.rance.chatui.util;

import com.rance.chatui.R;

import java.util.LinkedHashMap;

/**
 * 表情加载类,可自己添加多种表情，分别建立不同的map存放和不同的标志符即可
 */
public class EmotionUtils {

    /**
     * key-表情文字;
     * value-表情图片资源
     */
    public static LinkedHashMap<String, Integer> EMPTY_GIF_MAP;
    public static LinkedHashMap<String, Integer> EMOTION_STATIC_MAP;


    static {
        EMPTY_GIF_MAP = new LinkedHashMap<>();

//        表情
        EMPTY_GIF_MAP.put("[开心龇牙]", R.drawable.emoji_kaixinziya);
        EMPTY_GIF_MAP.put("[震惊]", R.drawable.emoji_zhenjing);
        EMPTY_GIF_MAP.put("[眨眼]", R.drawable.emoji_zhayan);
        EMPTY_GIF_MAP.put("[哭笑不得]", R.drawable.emoji_kuxiaobude);
        EMPTY_GIF_MAP.put("[可爱]", R.drawable.emoji_keai);
        EMPTY_GIF_MAP.put("[挑衅]", R.drawable.emoji_tiaoxin);
        EMPTY_GIF_MAP.put("[惆怅]", R.drawable.emoji_chouchang);
        EMPTY_GIF_MAP.put("[白眼]", R.drawable.emoji_baiyan);
        EMPTY_GIF_MAP.put("[大哭]", R.drawable.emoji_daku);
        EMPTY_GIF_MAP.put("[飞吻]", R.drawable.emoji_feiwen);
        EMPTY_GIF_MAP.put("[亲亲]", R.drawable.emoji_qinqin);
        EMPTY_GIF_MAP.put("[难过]", R.drawable.emoji_nanguo);
        EMPTY_GIF_MAP.put("[难受]", R.drawable.emoji_nanshou);
        EMPTY_GIF_MAP.put("[傲慢]", R.drawable.emoji_aoman);
        EMPTY_GIF_MAP.put("[扮鬼脸]", R.drawable.emoji_banguilian);
        EMPTY_GIF_MAP.put("[扮酷]", R.drawable.emoji_banku);
        EMPTY_GIF_MAP.put("[崩溃]", R.drawable.emoji_bengkui);
        EMPTY_GIF_MAP.put("[闭眼吐舌]", R.drawable.emoji_biyajtushe);
        EMPTY_GIF_MAP.put("[闭嘴]", R.drawable.emoji_bizui);
        EMPTY_GIF_MAP.put("[不高兴]", R.drawable.emoji_bugaoxing);
        EMPTY_GIF_MAP.put("[不开心]", R.drawable.emoji_bukaixin);
        EMPTY_GIF_MAP.put("[打瞌睡]", R.drawable.emoji_dakeshui);
        EMPTY_GIF_MAP.put("[大笑]", R.drawable.emoji_daxiao);
        EMPTY_GIF_MAP.put("[戴眼镜]", R.drawable.emoji_daiyanjing);
        EMPTY_GIF_MAP.put("[倒脸]", R.drawable.emoji_daolian);
        EMPTY_GIF_MAP.put("[滴汗]", R.drawable.emoji_dihan);
        EMPTY_GIF_MAP.put("[嘟嘴]", R.drawable.emoji_duzui);
        EMPTY_GIF_MAP.put("[欣慰]", R.drawable.emoji_wunai);  //无奈
        EMPTY_GIF_MAP.put("[斜眼看]", R.drawable.emoji_wunailian);  //无奈脸
        EMPTY_GIF_MAP.put("[发怒]", R.drawable.emoji_fanu);
        EMPTY_GIF_MAP.put("[生病]", R.drawable.emoji_shengbing);
        EMPTY_GIF_MAP.put("[发烧]", R.drawable.emoji_fashao);
        EMPTY_GIF_MAP.put("[受伤]", R.drawable.emoji_shoushang);
        EMPTY_GIF_MAP.put("[思考]", R.drawable.emoji_sikao);
        EMPTY_GIF_MAP.put("[烦躁]", R.drawable.emoji_fanzao);
        EMPTY_GIF_MAP.put("[犯困]", R.drawable.emoji_fankun);
        EMPTY_GIF_MAP.put("[尴尬]", R.drawable.emoji_ganga);
        EMPTY_GIF_MAP.put("[干瞪眼]", R.drawable.emoji_gandengyan);
        EMPTY_GIF_MAP.put("[高兴]", R.drawable.emoji_gaoxing);
        EMPTY_GIF_MAP.put("[黑脸微笑]", R.drawable.emoji_heilianweixiao);
        EMPTY_GIF_MAP.put("[神秘微笑]", R.drawable.emoji_shenmiweixiao);
        EMPTY_GIF_MAP.put("[哼]", R.drawable.emoji_heng);
        EMPTY_GIF_MAP.put("[花心]", R.drawable.emoji_huaxin);
        EMPTY_GIF_MAP.put("[欢喜]", R.drawable.emoji_huanxi);
        EMPTY_GIF_MAP.put("[慌张]", R.drawable.emoji_huangzhang);
        EMPTY_GIF_MAP.put("[开心]", R.drawable.emoji_kaixin);
        EMPTY_GIF_MAP.put("[看不懂]", R.drawable.emoji_kanbudong);
        EMPTY_GIF_MAP.put("[可爱眨眼]", R.drawable.emoji_keaizhayan);
        EMPTY_GIF_MAP.put("[脸红]", R.drawable.emoji_lianhong);
        EMPTY_GIF_MAP.put("[萌]", R.drawable.emoji_meng);
        EMPTY_GIF_MAP.put("[蒙圈]", R.drawable.emoji_mengquan);
        EMPTY_GIF_MAP.put("[面无表情]", R.drawable.emoji_mianwubiaoqing);
        EMPTY_GIF_MAP.put("[钱]", R.drawable.emoji_qian);
        EMPTY_GIF_MAP.put("[生气]", R.drawable.emoji_shengqi);
        EMPTY_GIF_MAP.put("[示弱]", R.drawable.emoji_shiruo);
        EMPTY_GIF_MAP.put("[摊手笑]", R.drawable.emoji_tanshouxiao);
        EMPTY_GIF_MAP.put("[天使微笑]", R.drawable.emoji_tianshiweixiao);
        EMPTY_GIF_MAP.put("[恶魔]", R.drawable.emoji_emo);
        EMPTY_GIF_MAP.put("[吐舌]", R.drawable.emoji_tushe);
        EMPTY_GIF_MAP.put("[无语]", R.drawable.emoji_wuyu);
        EMPTY_GIF_MAP.put("[龇牙]", R.drawable.emoji_ziya);
        EMPTY_GIF_MAP.put("[哑口无言]", R.drawable.emoji_yakouwuyan);
        EMPTY_GIF_MAP.put("[眼巴巴]", R.drawable.emoji_yanbaba);
        EMPTY_GIF_MAP.put("[张嘴]", R.drawable.emoji_zhangzui);
        EMPTY_GIF_MAP.put("[喜欢]", R.drawable.emoji_xihuan);
        EMPTY_GIF_MAP.put("[心虚]", R.drawable.emoji_xinxu);
        EMPTY_GIF_MAP.put("[月亮]", R.drawable.emoji_yueliang);
        EMPTY_GIF_MAP.put("[盯]", R.drawable.emoji_ding);

//        动植物
        EMPTY_GIF_MAP.put("[小老鼠]", R.drawable.emoji_xiaolaoshu);
        EMPTY_GIF_MAP.put("[小牛]", R.drawable.emoji_xiaoniu);
        EMPTY_GIF_MAP.put("[小老虎]", R.drawable.emoji_xiaolaohu);
        EMPTY_GIF_MAP.put("[小兔子]", R.drawable.emoji_xiaotuzi);
        EMPTY_GIF_MAP.put("[蛇]", R.drawable.emoji_she);
        EMPTY_GIF_MAP.put("[马头]", R.drawable.emoji_matou);
        EMPTY_GIF_MAP.put("[小绵羊]", R.drawable.emoji_xiaomianyang);
        EMPTY_GIF_MAP.put("[小猴]", R.drawable.emoji_xiaohou);
        EMPTY_GIF_MAP.put("[鸡]", R.drawable.emoji_ji);
        EMPTY_GIF_MAP.put("[小鸡]", R.drawable.emoji_xiaoji);
        EMPTY_GIF_MAP.put("[鸡蛋壳]", R.drawable.emoji_jidanke);
        EMPTY_GIF_MAP.put("[小汪狗]", R.drawable.emoji_xiaowanggou);
        EMPTY_GIF_MAP.put("[小猪]", R.drawable.emoji_xiaozhu);
        EMPTY_GIF_MAP.put("[大象]", R.drawable.emoji_daxiang);
        EMPTY_GIF_MAP.put("[大熊猫]", R.drawable.emoji_daxiongmao);
        EMPTY_GIF_MAP.put("[独角兽]", R.drawable.emoji_dujiaoshou);
        EMPTY_GIF_MAP.put("[鲸鱼]", R.drawable.emoji_jingyu);
        EMPTY_GIF_MAP.put("[毛毛虫]", R.drawable.emoji_maomaochong);
        EMPTY_GIF_MAP.put("[七星瓢虫]", R.drawable.emoji_qixingpiaochong);
        EMPTY_GIF_MAP.put("[小海豚]", R.drawable.emoji_xiaohaitun);
        EMPTY_GIF_MAP.put("[小蜜蜂]", R.drawable.emoji_xiaomifeng);
        EMPTY_GIF_MAP.put("[小青蛙]", R.drawable.emoji_xiaoqingwa);
        EMPTY_GIF_MAP.put("[小乌龟]", R.drawable.emoji_xiaowugui);
        EMPTY_GIF_MAP.put("[小熊]", R.drawable.emoji_xiaoxiong);
        EMPTY_GIF_MAP.put("[小鱼]", R.drawable.emoji_xiaoyu);
        EMPTY_GIF_MAP.put("[小章鱼]", R.drawable.emoji_xiaozhangyu);
        EMPTY_GIF_MAP.put("[樱花]", R.drawable.emoji_yinghua);
        EMPTY_GIF_MAP.put("[小红花]", R.drawable.emoji_xiaohonghua);
        EMPTY_GIF_MAP.put("[玫瑰]", R.drawable.emoji_meigui);
        EMPTY_GIF_MAP.put("[枫叶]", R.drawable.emoji_fengye);
        EMPTY_GIF_MAP.put("[落叶]", R.drawable.emoji_luoye);
        EMPTY_GIF_MAP.put("[四叶草]", R.drawable.emoji_siyecao);
        EMPTY_GIF_MAP.put("[仙人掌]", R.drawable.emoji_xianrenzhang);
        EMPTY_GIF_MAP.put("[圣诞树]", R.drawable.emoji_shengdanshu);
        EMPTY_GIF_MAP.put("[椰子树]", R.drawable.emoji_yezishu);
        EMPTY_GIF_MAP.put("[蘑菇]", R.drawable.emoji_mogu);
        EMPTY_GIF_MAP.put("[南瓜灯]", R.drawable.emoji_nanguadeng);
        EMPTY_GIF_MAP.put("[不看]", R.drawable.emoji_zheyanjing);   //遮眼睛
        EMPTY_GIF_MAP.put("[不说]", R.drawable.emoji_wuzui);  //捂嘴
        EMPTY_GIF_MAP.put("[不听]", R.drawable.emoji_wuerduo);  //捂耳朵


//        食物
        EMPTY_GIF_MAP.put("[苹果]", R.drawable.emoji_pingguo);
        EMPTY_GIF_MAP.put("[梨]", R.drawable.emoji_li);
        EMPTY_GIF_MAP.put("[草莓]", R.drawable.emoji_caomei);
        EMPTY_GIF_MAP.put("[葡萄]", R.drawable.emoji_putao);
        EMPTY_GIF_MAP.put("[哈蜜瓜]", R.drawable.emoji_hamigua);
        EMPTY_GIF_MAP.put("[桃子]", R.drawable.emoji_taozi);
        EMPTY_GIF_MAP.put("[西瓜]", R.drawable.emoji_xigua);
        EMPTY_GIF_MAP.put("[西红柿]", R.drawable.emoji_xihongshi);
        EMPTY_GIF_MAP.put("[樱桃]", R.drawable.emoji_yingtao);
        EMPTY_GIF_MAP.put("[茄子]", R.drawable.emoji_qiezi);
        EMPTY_GIF_MAP.put("[糖果]", R.drawable.emoji_tangguo);
        EMPTY_GIF_MAP.put("[棒棒糖]", R.drawable.emoji_bangbangtang);
        EMPTY_GIF_MAP.put("[爆米花]", R.drawable.emoji_baomihua);
        EMPTY_GIF_MAP.put("[冰淇淋]", R.drawable.emoji_bingqilin);
        EMPTY_GIF_MAP.put("[冰糖葫芦]", R.drawable.emoji_bingtanghulu);
        EMPTY_GIF_MAP.put("[吃冰]", R.drawable.emoji_chibing);
        EMPTY_GIF_MAP.put("[蛋糕]", R.drawable.emoji_dangao);
        EMPTY_GIF_MAP.put("[干杯]", R.drawable.emoji_ganbei);
        EMPTY_GIF_MAP.put("[汉堡]", R.drawable.emoji_hanbao);
        EMPTY_GIF_MAP.put("[喝果汁]", R.drawable.emoji_heguozhi);
        EMPTY_GIF_MAP.put("[茶]", R.drawable.emoji_mocha);  //抹茶
        EMPTY_GIF_MAP.put("[红酒]", R.drawable.emoji_hongjiu);
        EMPTY_GIF_MAP.put("[鸡尾酒]", R.drawable.emoji_jiweijiu);
        EMPTY_GIF_MAP.put("[煎蛋]", R.drawable.emoji_jiandan);
        EMPTY_GIF_MAP.put("[米饭]", R.drawable.emoji_mifan);
        EMPTY_GIF_MAP.put("[面]", R.drawable.emoji_mian);
        EMPTY_GIF_MAP.put("[面条]", R.drawable.emoji_miantiao);
        EMPTY_GIF_MAP.put("[面包]", R.drawable.emoji_mianbao);
        EMPTY_GIF_MAP.put("[薯条]", R.drawable.emoji_shutiao);
        EMPTY_GIF_MAP.put("[甜甜圈]", R.drawable.emoji_tiantianquan);
        EMPTY_GIF_MAP.put("[鸡腿]", R.drawable.emoji_jitui);
        EMPTY_GIF_MAP.put("[披萨]", R.drawable.emoji_pisa);
        EMPTY_GIF_MAP.put("[烧酒]", R.drawable.emoji_shaojiu);
        EMPTY_GIF_MAP.put("[寿司]", R.drawable.emoji_shousi);
        EMPTY_GIF_MAP.put("[盒饭]", R.drawable.emoji_hefan);

//        工具
        EMPTY_GIF_MAP.put("[棒球]", R.drawable.emoji_bangqiu);
        EMPTY_GIF_MAP.put("[电话]", R.drawable.emoji_dianhua);
        EMPTY_GIF_MAP.put("[动车]", R.drawable.emoji_dongche);
        EMPTY_GIF_MAP.put("[火箭]", R.drawable.emoji_huojian);
        EMPTY_GIF_MAP.put("[警车]", R.drawable.emoji_jingche);
        EMPTY_GIF_MAP.put("[救护车]", R.drawable.emoji_jiuhuche);
        EMPTY_GIF_MAP.put("[消防车]", R.drawable.emoji_xiaofangche);
        EMPTY_GIF_MAP.put("[直升机]", R.drawable.emoji_zhishengji);

//        其他
        EMPTY_GIF_MAP.put("[ok]", R.drawable.emoji_ok);
        EMPTY_GIF_MAP.put("[Rock]", R.drawable.emoji_rock);
        EMPTY_GIF_MAP.put("[鼓掌]", R.drawable.emoji_guzhang);
        EMPTY_GIF_MAP.put("[祈祷]", R.drawable.emoji_qidao);
        EMPTY_GIF_MAP.put("[手掌]", R.drawable.emoji_shouzhang);
        EMPTY_GIF_MAP.put("[摊手]", R.drawable.emoji_tanshou);
        EMPTY_GIF_MAP.put("[上面]", R.drawable.emoji_shangmian);
        EMPTY_GIF_MAP.put("[鼻子]", R.drawable.emoji_bizi);
        EMPTY_GIF_MAP.put("[耳朵]", R.drawable.emoji_erduo);
        EMPTY_GIF_MAP.put("[嘴巴]", R.drawable.emoji_zuiba);
        EMPTY_GIF_MAP.put("[鄙视]", R.drawable.emoji_bishi);
        EMPTY_GIF_MAP.put("[拳头]", R.drawable.emoji_quantou);
        EMPTY_GIF_MAP.put("[赞]", R.drawable.emoji_zan);
        EMPTY_GIF_MAP.put("[往上]", R.drawable.emoji_wangshang);
        EMPTY_GIF_MAP.put("[往下]", R.drawable.emoji_wangxia);
        EMPTY_GIF_MAP.put("[往左]", R.drawable.emoji_wangzuo);
        EMPTY_GIF_MAP.put("[往右]", R.drawable.emoji_wangyou);
        EMPTY_GIF_MAP.put("[举手]", R.drawable.emoji_jvshou);
        EMPTY_GIF_MAP.put("[拒绝]", R.drawable.emoji_jujue);
        EMPTY_GIF_MAP.put("[跑步]", R.drawable.emoji_paobu);
        EMPTY_GIF_MAP.put("[打球]", R.drawable.emoji_daqiu);
        EMPTY_GIF_MAP.put("[跳舞]", R.drawable.emoji_tiaowu);
        EMPTY_GIF_MAP.put("[爱情]", R.drawable.emoji_aiqing);
        EMPTY_GIF_MAP.put("[情侣]", R.drawable.emoji_qinglv);
        EMPTY_GIF_MAP.put("[夫妻]", R.drawable.emoji_fuqi);
        EMPTY_GIF_MAP.put("[蝴蝶结]", R.drawable.emoji_hudiejie);
        EMPTY_GIF_MAP.put("[花]", R.drawable.emoji_hua);
        EMPTY_GIF_MAP.put("[皇冠]", R.drawable.emoji_huangguan);
        EMPTY_GIF_MAP.put("[钻戒]", R.drawable.emoji_zuanjie);
        EMPTY_GIF_MAP.put("[口红]", R.drawable.emoji_kouhong);
        EMPTY_GIF_MAP.put("[礼花]", R.drawable.emoji_lihua);
        EMPTY_GIF_MAP.put("[礼物]", R.drawable.emoji_liwu);
        EMPTY_GIF_MAP.put("[庆祝]", R.drawable.emoji_qingzhu);
        EMPTY_GIF_MAP.put("[生日蛋糕]", R.drawable.emoji_shengridangao);
        EMPTY_GIF_MAP.put("[气球]", R.drawable.emoji_qiqiu);
        EMPTY_GIF_MAP.put("[情书]", R.drawable.emoji_qingshu);
        EMPTY_GIF_MAP.put("[钻石]", R.drawable.emoji_zuanshi);
        EMPTY_GIF_MAP.put("[T恤]", R.drawable.emoji_txu);
        EMPTY_GIF_MAP.put("[西装]", R.drawable.emoji_xizhuang);
        EMPTY_GIF_MAP.put("[牛仔裤]", R.drawable.emoji_niuzaiku);
        EMPTY_GIF_MAP.put("[高跟鞋]", R.drawable.emoji_gaogenxie);
        EMPTY_GIF_MAP.put("[裙子]", R.drawable.emoji_qunzi);
        EMPTY_GIF_MAP.put("[草帽]", R.drawable.emoji_caomao);
        EMPTY_GIF_MAP.put("[比基尼]", R.drawable.emoji_bijini);
        EMPTY_GIF_MAP.put("[和服]", R.drawable.emoji_hefu);
        EMPTY_GIF_MAP.put("[筒靴]", R.drawable.emoji_tongxue);
        EMPTY_GIF_MAP.put("[涂指甲]", R.drawable.emoji_tuzhijia);
        EMPTY_GIF_MAP.put("[眼镜]", R.drawable.emoji_yanjing);
        EMPTY_GIF_MAP.put("[红唇]", R.drawable.emoji_hongchun);
        EMPTY_GIF_MAP.put("[心]", R.drawable.emoji_xin);
        EMPTY_GIF_MAP.put("[心动]", R.drawable.emoji_xindong);
        EMPTY_GIF_MAP.put("[心碎]", R.drawable.emoji_xinsui);
        EMPTY_GIF_MAP.put("[爱心]", R.drawable.emoji_aixin);
        EMPTY_GIF_MAP.put("[粉色桃心]", R.drawable.emoji_fensetaoxin);
        EMPTY_GIF_MAP.put("[多云]", R.drawable.emoji_duoyun);
        EMPTY_GIF_MAP.put("[雷雨]", R.drawable.emoji_leiyu);
        EMPTY_GIF_MAP.put("[房子]", R.drawable.emoji_fangzi);
        EMPTY_GIF_MAP.put("[风铃]", R.drawable.emoji_fengling);
        EMPTY_GIF_MAP.put("[鬼脸]", R.drawable.emoji_guilian);
        EMPTY_GIF_MAP.put("[脚印]", R.drawable.emoji_jiaoyin);
        EMPTY_GIF_MAP.put("[鲤鱼旗]", R.drawable.emoji_liyuqi);
        EMPTY_GIF_MAP.put("[圣诞公公]", R.drawable.emoji_shengdangonggong);
        EMPTY_GIF_MAP.put("[雪人]", R.drawable.emoji_xueren);
        EMPTY_GIF_MAP.put("[药丸]", R.drawable.emoji_yaowan);
        EMPTY_GIF_MAP.put("[雨伞]", R.drawable.emoji_yusan);
        EMPTY_GIF_MAP.put("[炸弹]", R.drawable.emoji_zhadan);

//        EMPTY_GIF_MAP.put("[撇嘴]", R.drawable.emotion_biezui);
//        EMPTY_GIF_MAP.put("[色]", R.drawable.emotion_se);
//        EMPTY_GIF_MAP.put("[发呆]", R.drawable.emotion_fadai);
//        EMPTY_GIF_MAP.put("[得意]", R.drawable.emotion_deyi);
//        EMPTY_GIF_MAP.put("[流泪]", R.drawable.emotion_liulei);
//        EMPTY_GIF_MAP.put("[害羞]", R.drawable.emotion_haixiu);
//        EMPTY_GIF_MAP.put("[闭嘴]", R.drawable.emotion_bizui);
//        EMPTY_GIF_MAP.put("[睡]", R.drawable.emotion_shui);
//        EMPTY_GIF_MAP.put("[大哭]", R.drawable.emotion_daku);
//        EMPTY_GIF_MAP.put("[尴尬]", R.drawable.emotion_ganga);
//        EMPTY_GIF_MAP.put("[发怒]", R.drawable.emotion_fanu);
//        EMPTY_GIF_MAP.put("[调皮]", R.drawable.emotion_tiaopi);
//        EMPTY_GIF_MAP.put("[呲牙]", R.drawable.emotion_ciya);
//        EMPTY_GIF_MAP.put("[惊讶]", R.drawable.emotion_jingya);
//        EMPTY_GIF_MAP.put("[难过]", R.drawable.emotion_nanguo);
//        EMPTY_GIF_MAP.put("[酷]", R.drawable.emotion_ku);
//        EMPTY_GIF_MAP.put("[冷汗]", R.drawable.emotion_lenghan);
//        EMPTY_GIF_MAP.put("[抓狂]", R.drawable.emotion_zhuakuang);
//        EMPTY_GIF_MAP.put("[吐]", R.drawable.emotion_tu);
//        EMPTY_GIF_MAP.put("[偷笑]", R.drawable.emotion_touxiao);
//        EMPTY_GIF_MAP.put("[可爱]", R.drawable.emotion_keai);
//        EMPTY_GIF_MAP.put("[白眼]", R.drawable.emotion_baiyan);
//        EMPTY_GIF_MAP.put("[傲慢]", R.drawable.emotion_aoman);
//        EMPTY_GIF_MAP.put("[饥饿]", R.drawable.emotion_jie);
//        EMPTY_GIF_MAP.put("[困]", R.drawable.emotion_kun);
//        EMPTY_GIF_MAP.put("[惊恐]", R.drawable.emotion_jingkong);
//        EMPTY_GIF_MAP.put("[流汗]", R.drawable.emotion_liuhan);
//        EMPTY_GIF_MAP.put("[憨笑]", R.drawable.emotion_hanxiao);
//        EMPTY_GIF_MAP.put("[大兵]", R.drawable.emotion_dabing);
//        EMPTY_GIF_MAP.put("[奋斗]", R.drawable.emotion_fendou);
//        EMPTY_GIF_MAP.put("[咒骂]", R.drawable.emotion_zouma);
//        EMPTY_GIF_MAP.put("[疑问]", R.drawable.emotion_yiwen);
//        EMPTY_GIF_MAP.put("[嘘]", R.drawable.emotion_xu);
//        EMPTY_GIF_MAP.put("[晕]", R.drawable.emotion_yun);
//        EMPTY_GIF_MAP.put("[折磨]", R.drawable.emotion_fakuang);
//        EMPTY_GIF_MAP.put("[衰]", R.drawable.emotion_shuai);
//        EMPTY_GIF_MAP.put("[骷髅]", R.drawable.emotion_kulou);
//        EMPTY_GIF_MAP.put("[敲打]", R.drawable.emotion_qiaoda);
//        EMPTY_GIF_MAP.put("[再见]", R.drawable.emotion_zaijian);
//        EMPTY_GIF_MAP.put("[擦汗]", R.drawable.emotion_cahan);
//        EMPTY_GIF_MAP.put("[抠鼻]", R.drawable.emotion_koubi);
//        EMPTY_GIF_MAP.put("[鼓掌]", R.drawable.emotion_guzhang);
//        EMPTY_GIF_MAP.put("[糗大了]", R.drawable.emotion_qiudale);
//        EMPTY_GIF_MAP.put("[坏笑]", R.drawable.emotion_huaixiao);
//        EMPTY_GIF_MAP.put("[左哼哼]", R.drawable.emotion_zuohengheng);
//        EMPTY_GIF_MAP.put("[右哼哼]", R.drawable.emotion_youhengheng);
//        EMPTY_GIF_MAP.put("[哈欠]", R.drawable.emotion_haqian);
//        EMPTY_GIF_MAP.put("[鄙视]", R.drawable.emotion_bishi);
//        EMPTY_GIF_MAP.put("[委屈]", R.drawable.emotion_weiqu);
//        EMPTY_GIF_MAP.put("[快哭了]", R.drawable.emotion_kuaikule);
//        EMPTY_GIF_MAP.put("[阴险]", R.drawable.emotion_yingxian);
//        EMPTY_GIF_MAP.put("[亲亲]", R.drawable.emotion_qinqin);
//        EMPTY_GIF_MAP.put("[吓]", R.drawable.emotion_xia);
//        EMPTY_GIF_MAP.put("[可怜]", R.drawable.emotion_kelian);
//        EMPTY_GIF_MAP.put("[菜刀]", R.drawable.emotion_caidao);
//        EMPTY_GIF_MAP.put("[西瓜]", R.drawable.emotion_xigua);
//        EMPTY_GIF_MAP.put("[啤酒]", R.drawable.emotion_pijiu);
//        EMPTY_GIF_MAP.put("[篮球]", R.drawable.emotion_lanqiu);
//        EMPTY_GIF_MAP.put("[乒乓]", R.drawable.emotion_pingpang);
//        EMPTY_GIF_MAP.put("[咖啡]", R.drawable.emotion_kafei);
//        EMPTY_GIF_MAP.put("[饭]", R.drawable.emotion_fan);
//        EMPTY_GIF_MAP.put("[猪头]", R.drawable.emotion_zhutou);
//        EMPTY_GIF_MAP.put("[玫瑰]", R.drawable.emotion_meigui);
//        EMPTY_GIF_MAP.put("[凋谢]", R.drawable.emotion_diaoxie);
//        EMPTY_GIF_MAP.put("[示爱]", R.drawable.emotion_shiai);
//        EMPTY_GIF_MAP.put("[爱心]", R.drawable.emotion_aixin);
//        EMPTY_GIF_MAP.put("[心碎]", R.drawable.emotion_xinsui);
//        EMPTY_GIF_MAP.put("[蛋糕]", R.drawable.emotion_dangao);
//        EMPTY_GIF_MAP.put("[闪电]", R.drawable.emotion_shandian);
//        EMPTY_GIF_MAP.put("[炸弹]", R.drawable.emotion_zhadan);
//        EMPTY_GIF_MAP.put("[刀]", R.drawable.emotion_dao);
//        EMPTY_GIF_MAP.put("[足球]", R.drawable.emotion_zhuqiu);
//        EMPTY_GIF_MAP.put("[瓢虫]", R.drawable.emotion_pachong);
//        EMPTY_GIF_MAP.put("[便便]", R.drawable.emotion_bianbian);
//        EMPTY_GIF_MAP.put("[月亮]", R.drawable.emotion_yueliang);
//        EMPTY_GIF_MAP.put("[太阳]", R.drawable.emotion_taiyang);
//        EMPTY_GIF_MAP.put("[礼物]", R.drawable.emotion_liwu);
//        EMPTY_GIF_MAP.put("[拥抱]", R.drawable.emotion_baobao);
//        EMPTY_GIF_MAP.put("[强]", R.drawable.emotion_qiang);
//        EMPTY_GIF_MAP.put("[弱]", R.drawable.emotion_ruo);
//        EMPTY_GIF_MAP.put("[握手]", R.drawable.emotion_woshou);
//        EMPTY_GIF_MAP.put("[胜利]", R.drawable.emotion_shengli);
//        EMPTY_GIF_MAP.put("[抱拳]", R.drawable.emotion_baoquan);
//        EMPTY_GIF_MAP.put("[勾引]", R.drawable.emotion_gouying);
//        EMPTY_GIF_MAP.put("[拳头]", R.drawable.emotion_quantou);
//        EMPTY_GIF_MAP.put("[差劲]", R.drawable.emotion_chajing);
//        EMPTY_GIF_MAP.put("[爱你]", R.drawable.emotion_aini);
//        EMPTY_GIF_MAP.put("[NO]", R.drawable.emotion_no);
//        EMPTY_GIF_MAP.put("[OK]", R.drawable.emotion_ok);
//        EMPTY_GIF_MAP.put("[爱情]", R.drawable.emotion_aiqing);
//        EMPTY_GIF_MAP.put("[飞吻]", R.drawable.emotion_feiwen);
//        EMPTY_GIF_MAP.put("[跳跳]", R.drawable.emotion_tiaotiao);
//        EMPTY_GIF_MAP.put("[发抖]", R.drawable.emotion_fadou);
//        EMPTY_GIF_MAP.put("[怄火]", R.drawable.emotion_ouhuo);
//        EMPTY_GIF_MAP.put("[转圈]", R.drawable.emotion_zhuanquan);
//        EMPTY_GIF_MAP.put("[磕头]", R.drawable.emotion_ketou);
//        EMPTY_GIF_MAP.put("[回头]", R.drawable.emotion_huitou);
//        EMPTY_GIF_MAP.put("[跳绳]", R.drawable.emotion_tiaosheng);
//        EMPTY_GIF_MAP.put("[挥手]", R.drawable.emotion_huishou);
//        EMPTY_GIF_MAP.put("[激动]", R.drawable.emotion_jidong);
//        EMPTY_GIF_MAP.put("[街舞]", R.drawable.emotion_jiewu);
//        EMPTY_GIF_MAP.put("[献吻]", R.drawable.emotion_xianwen);
//        EMPTY_GIF_MAP.put("[左太极]", R.drawable.emotion_zuotaiji);
//        EMPTY_GIF_MAP.put("[右太极]", R.drawable.emotion_youtaiji);
//        EMPTY_GIF_MAP.put("[双喜]", R.drawable.emotion_shuangxi);
//        EMPTY_GIF_MAP.put("[鞭炮]", R.drawable.emotion_bianpao);
//        EMPTY_GIF_MAP.put("[灯笼]", R.drawable.emotion_denglong);
//        EMPTY_GIF_MAP.put("[发财]", R.drawable.emotion_facai);
//        EMPTY_GIF_MAP.put("[K歌]", R.drawable.emotion_kge);
//        EMPTY_GIF_MAP.put("[购物]", R.drawable.emotion_gouwu);
//        EMPTY_GIF_MAP.put("[邮件]", R.drawable.emotion_youjian);
//        EMPTY_GIF_MAP.put("[帅]", R.drawable.emotion_dashuai);
//        EMPTY_GIF_MAP.put("[喝彩]", R.drawable.emotion_hecai);
//        EMPTY_GIF_MAP.put("[祈祷]", R.drawable.emotion_qidao);
//        EMPTY_GIF_MAP.put("[爆筋]", R.drawable.emotion_baojing);
//        EMPTY_GIF_MAP.put("[棒棒糖]", R.drawable.emotion_bangbangtang);
//        EMPTY_GIF_MAP.put("[喝奶]", R.drawable.emotion_henai);
//        EMPTY_GIF_MAP.put("[下面]", R.drawable.emotion_xiamian);
//        EMPTY_GIF_MAP.put("[香蕉]", R.drawable.emotion_xiangjiao);
//        EMPTY_GIF_MAP.put("[飞机]", R.drawable.emotion_feiji);
//        EMPTY_GIF_MAP.put("[开车]", R.drawable.emotion_kaiche);
//        EMPTY_GIF_MAP.put("[左车头]", R.drawable.emotion_zuochetou);
//        EMPTY_GIF_MAP.put("[车厢]", R.drawable.emotion_chexiang);
//        EMPTY_GIF_MAP.put("[右车头]", R.drawable.emotion_youchexiang);
//        EMPTY_GIF_MAP.put("[多云]", R.drawable.emotion_duoyun);
//        EMPTY_GIF_MAP.put("[下雨]", R.drawable.emotion_xiayu);
//        EMPTY_GIF_MAP.put("[钞票]", R.drawable.emotion_chaopiao);
//        EMPTY_GIF_MAP.put("[熊猫]", R.drawable.emotion_xiongmao);
//        EMPTY_GIF_MAP.put("[灯泡]", R.drawable.emotion_dengpao);
//        EMPTY_GIF_MAP.put("[风车]", R.drawable.emotion_fengche);
//        EMPTY_GIF_MAP.put("[闹钟]", R.drawable.emotion_naozhong);
//        EMPTY_GIF_MAP.put("[打伞]", R.drawable.emotion_dashan);
//        EMPTY_GIF_MAP.put("[彩球]", R.drawable.emotion_caiqiu);
//        EMPTY_GIF_MAP.put("[钻戒]", R.drawable.emotion_zhuanjie);
//        EMPTY_GIF_MAP.put("[沙发]", R.drawable.emotion_shafa);
//        EMPTY_GIF_MAP.put("[纸巾]", R.drawable.emotion_zhijing);
//        EMPTY_GIF_MAP.put("[药]", R.drawable.emotion_yao);
//        EMPTY_GIF_MAP.put("[手枪]", R.drawable.emotion_shouqiang);
//        EMPTY_GIF_MAP.put("[青蛙]", R.drawable.emotion_qingwa);

        EMOTION_STATIC_MAP = new LinkedHashMap<>();

        //        表情
        EMOTION_STATIC_MAP.put("[开心龇牙]", R.drawable.emoji_kaixinziya);
        EMOTION_STATIC_MAP.put("[震惊]", R.drawable.emoji_zhenjing);
        EMOTION_STATIC_MAP.put("[眨眼]", R.drawable.emoji_zhayan);
        EMOTION_STATIC_MAP.put("[哭笑不得]", R.drawable.emoji_kuxiaobude);
        EMOTION_STATIC_MAP.put("[可爱]", R.drawable.emoji_keai);
        EMOTION_STATIC_MAP.put("[挑衅]", R.drawable.emoji_tiaoxin);
        EMOTION_STATIC_MAP.put("[惆怅]", R.drawable.emoji_chouchang);
        EMOTION_STATIC_MAP.put("[白眼]", R.drawable.emoji_baiyan);
        EMOTION_STATIC_MAP.put("[大哭]", R.drawable.emoji_daku);
        EMOTION_STATIC_MAP.put("[飞吻]", R.drawable.emoji_feiwen);
        EMOTION_STATIC_MAP.put("[亲亲]", R.drawable.emoji_qinqin);
        EMOTION_STATIC_MAP.put("[难过]", R.drawable.emoji_nanguo);
        EMOTION_STATIC_MAP.put("[难受]", R.drawable.emoji_nanshou);
        EMOTION_STATIC_MAP.put("[傲慢]", R.drawable.emoji_aoman);
        EMOTION_STATIC_MAP.put("[扮鬼脸]", R.drawable.emoji_banguilian);
        EMOTION_STATIC_MAP.put("[扮酷]", R.drawable.emoji_banku);
        EMOTION_STATIC_MAP.put("[崩溃]", R.drawable.emoji_bengkui);
        EMOTION_STATIC_MAP.put("[闭眼吐舌]", R.drawable.emoji_biyajtushe);
        EMOTION_STATIC_MAP.put("[闭嘴]", R.drawable.emoji_bizui);
        EMOTION_STATIC_MAP.put("[不高兴]", R.drawable.emoji_bugaoxing);
        EMOTION_STATIC_MAP.put("[不开心]", R.drawable.emoji_bukaixin);
        EMOTION_STATIC_MAP.put("[打瞌睡]", R.drawable.emoji_dakeshui);
        EMOTION_STATIC_MAP.put("[大笑]", R.drawable.emoji_daxiao);
        EMOTION_STATIC_MAP.put("[戴眼镜]", R.drawable.emoji_daiyanjing);
        EMOTION_STATIC_MAP.put("[倒脸]", R.drawable.emoji_daolian);
        EMOTION_STATIC_MAP.put("[滴汗]", R.drawable.emoji_dihan);
        EMOTION_STATIC_MAP.put("[嘟嘴]", R.drawable.emoji_duzui);
        EMOTION_STATIC_MAP.put("[欣慰]", R.drawable.emoji_wunai);  //无奈
        EMOTION_STATIC_MAP.put("[斜眼看]", R.drawable.emoji_wunailian);  //无奈脸
        EMOTION_STATIC_MAP.put("[发怒]", R.drawable.emoji_fanu);
        EMOTION_STATIC_MAP.put("[生病]", R.drawable.emoji_shengbing);
        EMOTION_STATIC_MAP.put("[发烧]", R.drawable.emoji_fashao);
        EMOTION_STATIC_MAP.put("[受伤]", R.drawable.emoji_shoushang);
        EMOTION_STATIC_MAP.put("[思考]", R.drawable.emoji_sikao);
        EMOTION_STATIC_MAP.put("[烦躁]", R.drawable.emoji_fanzao);
        EMOTION_STATIC_MAP.put("[犯困]", R.drawable.emoji_fankun);
        EMOTION_STATIC_MAP.put("[尴尬]", R.drawable.emoji_ganga);
        EMOTION_STATIC_MAP.put("[干瞪眼]", R.drawable.emoji_gandengyan);
        EMOTION_STATIC_MAP.put("[高兴]", R.drawable.emoji_gaoxing);
        EMOTION_STATIC_MAP.put("[黑脸微笑]", R.drawable.emoji_heilianweixiao);
        EMOTION_STATIC_MAP.put("[神秘微笑]", R.drawable.emoji_shenmiweixiao);
        EMOTION_STATIC_MAP.put("[哼]", R.drawable.emoji_heng);
        EMOTION_STATIC_MAP.put("[花心]", R.drawable.emoji_huaxin);
        EMOTION_STATIC_MAP.put("[欢喜]", R.drawable.emoji_huanxi);
        EMOTION_STATIC_MAP.put("[慌张]", R.drawable.emoji_huangzhang);
        EMOTION_STATIC_MAP.put("[开心]", R.drawable.emoji_kaixin);
        EMOTION_STATIC_MAP.put("[看不懂]", R.drawable.emoji_kanbudong);
        EMOTION_STATIC_MAP.put("[可爱眨眼]", R.drawable.emoji_keaizhayan);
        EMOTION_STATIC_MAP.put("[脸红]", R.drawable.emoji_lianhong);
        EMOTION_STATIC_MAP.put("[萌]", R.drawable.emoji_meng);
        EMOTION_STATIC_MAP.put("[蒙圈]", R.drawable.emoji_mengquan);
        EMOTION_STATIC_MAP.put("[面无表情]", R.drawable.emoji_mianwubiaoqing);
        EMOTION_STATIC_MAP.put("[钱]", R.drawable.emoji_qian);
        EMOTION_STATIC_MAP.put("[生气]", R.drawable.emoji_shengqi);
        EMOTION_STATIC_MAP.put("[示弱]", R.drawable.emoji_shiruo);
        EMOTION_STATIC_MAP.put("[摊手笑]", R.drawable.emoji_tanshouxiao);
        EMOTION_STATIC_MAP.put("[天使微笑]", R.drawable.emoji_tianshiweixiao);
        EMOTION_STATIC_MAP.put("[恶魔]", R.drawable.emoji_emo);
        EMOTION_STATIC_MAP.put("[吐舌]", R.drawable.emoji_tushe);
        EMOTION_STATIC_MAP.put("[无语]", R.drawable.emoji_wuyu);
        EMOTION_STATIC_MAP.put("[龇牙]", R.drawable.emoji_ziya);
        EMOTION_STATIC_MAP.put("[哑口无言]", R.drawable.emoji_yakouwuyan);
        EMOTION_STATIC_MAP.put("[眼巴巴]", R.drawable.emoji_yanbaba);
        EMOTION_STATIC_MAP.put("[张嘴]", R.drawable.emoji_zhangzui);
        EMOTION_STATIC_MAP.put("[喜欢]", R.drawable.emoji_xihuan);
        EMOTION_STATIC_MAP.put("[心虚]", R.drawable.emoji_xinxu);
        EMOTION_STATIC_MAP.put("[月亮]", R.drawable.emoji_yueliang);
        EMOTION_STATIC_MAP.put("[盯]", R.drawable.emoji_ding);

//        动植物
        EMOTION_STATIC_MAP.put("[小老鼠]", R.drawable.emoji_xiaolaoshu);
        EMOTION_STATIC_MAP.put("[小牛]", R.drawable.emoji_xiaoniu);
        EMOTION_STATIC_MAP.put("[小老虎]", R.drawable.emoji_xiaolaohu);
        EMOTION_STATIC_MAP.put("[小兔子]", R.drawable.emoji_xiaotuzi);
        EMOTION_STATIC_MAP.put("[蛇]", R.drawable.emoji_she);
        EMOTION_STATIC_MAP.put("[马头]", R.drawable.emoji_matou);
        EMOTION_STATIC_MAP.put("[小绵羊]", R.drawable.emoji_xiaomianyang);
        EMOTION_STATIC_MAP.put("[小猴]", R.drawable.emoji_xiaohou);
        EMOTION_STATIC_MAP.put("[鸡]", R.drawable.emoji_ji);
        EMOTION_STATIC_MAP.put("[小鸡]", R.drawable.emoji_xiaoji);
        EMOTION_STATIC_MAP.put("[鸡蛋壳]", R.drawable.emoji_jidanke);
        EMOTION_STATIC_MAP.put("[小汪狗]", R.drawable.emoji_xiaowanggou);
        EMOTION_STATIC_MAP.put("[小猪]", R.drawable.emoji_xiaozhu);
        EMOTION_STATIC_MAP.put("[大象]", R.drawable.emoji_daxiang);
        EMOTION_STATIC_MAP.put("[大熊猫]", R.drawable.emoji_daxiongmao);
        EMOTION_STATIC_MAP.put("[独角兽]", R.drawable.emoji_dujiaoshou);
        EMOTION_STATIC_MAP.put("[鲸鱼]", R.drawable.emoji_jingyu);
        EMOTION_STATIC_MAP.put("[毛毛虫]", R.drawable.emoji_maomaochong);
        EMOTION_STATIC_MAP.put("[七星瓢虫]", R.drawable.emoji_qixingpiaochong);
        EMOTION_STATIC_MAP.put("[小海豚]", R.drawable.emoji_xiaohaitun);
        EMOTION_STATIC_MAP.put("[小蜜蜂]", R.drawable.emoji_xiaomifeng);
        EMOTION_STATIC_MAP.put("[小青蛙]", R.drawable.emoji_xiaoqingwa);
        EMOTION_STATIC_MAP.put("[小乌龟]", R.drawable.emoji_xiaowugui);
        EMOTION_STATIC_MAP.put("[小熊]", R.drawable.emoji_xiaoxiong);
        EMOTION_STATIC_MAP.put("[小鱼]", R.drawable.emoji_xiaoyu);
        EMOTION_STATIC_MAP.put("[小章鱼]", R.drawable.emoji_xiaozhangyu);
        EMOTION_STATIC_MAP.put("[樱花]", R.drawable.emoji_yinghua);
        EMOTION_STATIC_MAP.put("[小红花]", R.drawable.emoji_xiaohonghua);
        EMOTION_STATIC_MAP.put("[玫瑰]", R.drawable.emoji_meigui);
        EMOTION_STATIC_MAP.put("[枫叶]", R.drawable.emoji_fengye);
        EMOTION_STATIC_MAP.put("[落叶]", R.drawable.emoji_luoye);
        EMOTION_STATIC_MAP.put("[四叶草]", R.drawable.emoji_siyecao);
        EMOTION_STATIC_MAP.put("[仙人掌]", R.drawable.emoji_xianrenzhang);
        EMOTION_STATIC_MAP.put("[圣诞树]", R.drawable.emoji_shengdanshu);
        EMOTION_STATIC_MAP.put("[椰子树]", R.drawable.emoji_yezishu);
        EMOTION_STATIC_MAP.put("[蘑菇]", R.drawable.emoji_mogu);
        EMOTION_STATIC_MAP.put("[南瓜灯]", R.drawable.emoji_nanguadeng);
        EMOTION_STATIC_MAP.put("[不看]", R.drawable.emoji_zheyanjing);   //遮眼睛
        EMOTION_STATIC_MAP.put("[不说]", R.drawable.emoji_wuzui);  //捂嘴
        EMOTION_STATIC_MAP.put("[不听]", R.drawable.emoji_wuerduo);  //捂耳朵


//        食物
        EMOTION_STATIC_MAP.put("[苹果]", R.drawable.emoji_pingguo);
        EMOTION_STATIC_MAP.put("[梨]", R.drawable.emoji_li);
        EMOTION_STATIC_MAP.put("[草莓]", R.drawable.emoji_caomei);
        EMOTION_STATIC_MAP.put("[葡萄]", R.drawable.emoji_putao);
        EMOTION_STATIC_MAP.put("[哈蜜瓜]", R.drawable.emoji_hamigua);
        EMOTION_STATIC_MAP.put("[桃子]", R.drawable.emoji_taozi);
        EMOTION_STATIC_MAP.put("[西瓜]", R.drawable.emoji_xigua);
        EMOTION_STATIC_MAP.put("[西红柿]", R.drawable.emoji_xihongshi);
        EMOTION_STATIC_MAP.put("[樱桃]", R.drawable.emoji_yingtao);
        EMOTION_STATIC_MAP.put("[茄子]", R.drawable.emoji_qiezi);
        EMOTION_STATIC_MAP.put("[糖果]", R.drawable.emoji_tangguo);
        EMOTION_STATIC_MAP.put("[棒棒糖]", R.drawable.emoji_bangbangtang);
        EMOTION_STATIC_MAP.put("[爆米花]", R.drawable.emoji_baomihua);
        EMOTION_STATIC_MAP.put("[冰淇淋]", R.drawable.emoji_bingqilin);
        EMOTION_STATIC_MAP.put("[冰糖葫芦]", R.drawable.emoji_bingtanghulu);
        EMOTION_STATIC_MAP.put("[吃冰]", R.drawable.emoji_chibing);
        EMOTION_STATIC_MAP.put("[蛋糕]", R.drawable.emoji_dangao);
        EMOTION_STATIC_MAP.put("[干杯]", R.drawable.emoji_ganbei);
        EMOTION_STATIC_MAP.put("[汉堡]", R.drawable.emoji_hanbao);
        EMOTION_STATIC_MAP.put("[喝果汁]", R.drawable.emoji_heguozhi);
        EMOTION_STATIC_MAP.put("[茶]", R.drawable.emoji_mocha);  //抹茶
        EMOTION_STATIC_MAP.put("[红酒]", R.drawable.emoji_hongjiu);
        EMOTION_STATIC_MAP.put("[鸡尾酒]", R.drawable.emoji_jiweijiu);
        EMOTION_STATIC_MAP.put("[煎蛋]", R.drawable.emoji_jiandan);
        EMOTION_STATIC_MAP.put("[米饭]", R.drawable.emoji_mifan);
        EMOTION_STATIC_MAP.put("[面]", R.drawable.emoji_mian);
        EMOTION_STATIC_MAP.put("[面条]", R.drawable.emoji_miantiao);
        EMOTION_STATIC_MAP.put("[面包]", R.drawable.emoji_mianbao);
        EMOTION_STATIC_MAP.put("[薯条]", R.drawable.emoji_shutiao);
        EMOTION_STATIC_MAP.put("[甜甜圈]", R.drawable.emoji_tiantianquan);
        EMOTION_STATIC_MAP.put("[鸡腿]", R.drawable.emoji_jitui);
        EMOTION_STATIC_MAP.put("[披萨]", R.drawable.emoji_pisa);
        EMOTION_STATIC_MAP.put("[烧酒]", R.drawable.emoji_shaojiu);
        EMOTION_STATIC_MAP.put("[寿司]", R.drawable.emoji_shousi);
        EMOTION_STATIC_MAP.put("[盒饭]", R.drawable.emoji_hefan);

//        工具
        EMOTION_STATIC_MAP.put("[棒球]", R.drawable.emoji_bangqiu);
        EMOTION_STATIC_MAP.put("[电话]", R.drawable.emoji_dianhua);
        EMOTION_STATIC_MAP.put("[动车]", R.drawable.emoji_dongche);
        EMOTION_STATIC_MAP.put("[火箭]", R.drawable.emoji_huojian);
        EMOTION_STATIC_MAP.put("[警车]", R.drawable.emoji_jingche);
        EMOTION_STATIC_MAP.put("[救护车]", R.drawable.emoji_jiuhuche);
        EMOTION_STATIC_MAP.put("[消防车]", R.drawable.emoji_xiaofangche);
        EMOTION_STATIC_MAP.put("[直升机]", R.drawable.emoji_zhishengji);

//        其他
        EMOTION_STATIC_MAP.put("[ok]", R.drawable.emoji_ok);
        EMOTION_STATIC_MAP.put("[Rock]", R.drawable.emoji_rock);
        EMOTION_STATIC_MAP.put("[鼓掌]", R.drawable.emoji_guzhang);
        EMOTION_STATIC_MAP.put("[祈祷]", R.drawable.emoji_qidao);
        EMOTION_STATIC_MAP.put("[手掌]", R.drawable.emoji_shouzhang);
        EMOTION_STATIC_MAP.put("[摊手]", R.drawable.emoji_tanshou);
        EMOTION_STATIC_MAP.put("[上面]", R.drawable.emoji_shangmian);
        EMOTION_STATIC_MAP.put("[鼻子]", R.drawable.emoji_bizi);
        EMOTION_STATIC_MAP.put("[耳朵]", R.drawable.emoji_erduo);
        EMOTION_STATIC_MAP.put("[嘴巴]", R.drawable.emoji_zuiba);
        EMOTION_STATIC_MAP.put("[鄙视]", R.drawable.emoji_bishi);
        EMOTION_STATIC_MAP.put("[拳头]", R.drawable.emoji_quantou);
        EMOTION_STATIC_MAP.put("[赞]", R.drawable.emoji_zan);
        EMOTION_STATIC_MAP.put("[往上]", R.drawable.emoji_wangshang);
        EMOTION_STATIC_MAP.put("[往下]", R.drawable.emoji_wangxia);
        EMOTION_STATIC_MAP.put("[往左]", R.drawable.emoji_wangzuo);
        EMOTION_STATIC_MAP.put("[往右]", R.drawable.emoji_wangyou);
        EMOTION_STATIC_MAP.put("[举手]", R.drawable.emoji_jvshou);
        EMOTION_STATIC_MAP.put("[拒绝]", R.drawable.emoji_jujue);
        EMOTION_STATIC_MAP.put("[跑步]", R.drawable.emoji_paobu);
        EMOTION_STATIC_MAP.put("[打球]", R.drawable.emoji_daqiu);
        EMOTION_STATIC_MAP.put("[跳舞]", R.drawable.emoji_tiaowu);
        EMOTION_STATIC_MAP.put("[爱情]", R.drawable.emoji_aiqing);
        EMOTION_STATIC_MAP.put("[情侣]", R.drawable.emoji_qinglv);
        EMOTION_STATIC_MAP.put("[夫妻]", R.drawable.emoji_fuqi);
        EMOTION_STATIC_MAP.put("[蝴蝶结]", R.drawable.emoji_hudiejie);
        EMOTION_STATIC_MAP.put("[花]", R.drawable.emoji_hua);
        EMOTION_STATIC_MAP.put("[皇冠]", R.drawable.emoji_huangguan);
        EMOTION_STATIC_MAP.put("[钻戒]", R.drawable.emoji_zuanjie);
        EMOTION_STATIC_MAP.put("[口红]", R.drawable.emoji_kouhong);
        EMOTION_STATIC_MAP.put("[礼花]", R.drawable.emoji_lihua);
        EMOTION_STATIC_MAP.put("[礼物]", R.drawable.emoji_liwu);
        EMOTION_STATIC_MAP.put("[庆祝]", R.drawable.emoji_qingzhu);
        EMOTION_STATIC_MAP.put("[生日蛋糕]", R.drawable.emoji_shengridangao);
        EMOTION_STATIC_MAP.put("[气球]", R.drawable.emoji_qiqiu);
        EMOTION_STATIC_MAP.put("[情书]", R.drawable.emoji_qingshu);
        EMOTION_STATIC_MAP.put("[钻石]", R.drawable.emoji_zuanshi);
        EMOTION_STATIC_MAP.put("[T恤]", R.drawable.emoji_txu);
        EMOTION_STATIC_MAP.put("[西装]", R.drawable.emoji_xizhuang);
        EMOTION_STATIC_MAP.put("[牛仔裤]", R.drawable.emoji_niuzaiku);
        EMOTION_STATIC_MAP.put("[高跟鞋]", R.drawable.emoji_gaogenxie);
        EMOTION_STATIC_MAP.put("[裙子]", R.drawable.emoji_qunzi);
        EMOTION_STATIC_MAP.put("[草帽]", R.drawable.emoji_caomao);
        EMOTION_STATIC_MAP.put("[比基尼]", R.drawable.emoji_bijini);
        EMOTION_STATIC_MAP.put("[和服]", R.drawable.emoji_hefu);
        EMOTION_STATIC_MAP.put("[筒靴]", R.drawable.emoji_tongxue);
        EMOTION_STATIC_MAP.put("[涂指甲]", R.drawable.emoji_tuzhijia);
        EMOTION_STATIC_MAP.put("[眼镜]", R.drawable.emoji_yanjing);
        EMOTION_STATIC_MAP.put("[红唇]", R.drawable.emoji_hongchun);
        EMOTION_STATIC_MAP.put("[心]", R.drawable.emoji_xin);
        EMOTION_STATIC_MAP.put("[心动]", R.drawable.emoji_xindong);
        EMOTION_STATIC_MAP.put("[心碎]", R.drawable.emoji_xinsui);
        EMOTION_STATIC_MAP.put("[爱心]", R.drawable.emoji_aixin);
        EMOTION_STATIC_MAP.put("[粉色桃心]", R.drawable.emoji_fensetaoxin);
        EMOTION_STATIC_MAP.put("[多云]", R.drawable.emoji_duoyun);
        EMOTION_STATIC_MAP.put("[雷雨]", R.drawable.emoji_leiyu);
        EMOTION_STATIC_MAP.put("[房子]", R.drawable.emoji_fangzi);
        EMOTION_STATIC_MAP.put("[风铃]", R.drawable.emoji_fengling);
        EMOTION_STATIC_MAP.put("[鬼脸]", R.drawable.emoji_guilian);
        EMOTION_STATIC_MAP.put("[脚印]", R.drawable.emoji_jiaoyin);
        EMOTION_STATIC_MAP.put("[鲤鱼旗]", R.drawable.emoji_liyuqi);
        EMOTION_STATIC_MAP.put("[圣诞公公]", R.drawable.emoji_shengdangonggong);
        EMOTION_STATIC_MAP.put("[雪人]", R.drawable.emoji_xueren);
        EMOTION_STATIC_MAP.put("[药丸]", R.drawable.emoji_yaowan);
        EMOTION_STATIC_MAP.put("[雨伞]", R.drawable.emoji_yusan);
        EMOTION_STATIC_MAP.put("[炸弹]", R.drawable.emoji_zhadan);

//        EMOTION_STATIC_MAP.put("[微笑]", R.drawable.emotion_weixiao);
//        EMOTION_STATIC_MAP.put("[撇嘴]", R.drawable.emotion_biezui);
//        EMOTION_STATIC_MAP.put("[色]", R.drawable.emotion_se);
//        EMOTION_STATIC_MAP.put("[发呆]", R.drawable.emotion_fadai);
//        EMOTION_STATIC_MAP.put("[得意]", R.drawable.emotion_deyi);
//        EMOTION_STATIC_MAP.put("[流泪]", R.drawable.emotion_liulei);
//        EMOTION_STATIC_MAP.put("[害羞]", R.drawable.emotion_haixiu);
//        EMOTION_STATIC_MAP.put("[闭嘴]", R.drawable.emotion_bizui);
//        EMOTION_STATIC_MAP.put("[睡]", R.drawable.emotion_shui);
//        EMOTION_STATIC_MAP.put("[大哭]", R.drawable.emotion_daku);
//        EMOTION_STATIC_MAP.put("[尴尬]", R.drawable.emotion_ganga);
//        EMOTION_STATIC_MAP.put("[发怒]", R.drawable.emotion_fanu);
//        EMOTION_STATIC_MAP.put("[调皮]", R.drawable.emotion_tiaopi);
//        EMOTION_STATIC_MAP.put("[呲牙]", R.drawable.emotion_ciya);
//        EMOTION_STATIC_MAP.put("[惊讶]", R.drawable.emotion_jingya);
//        EMOTION_STATIC_MAP.put("[难过]", R.drawable.emotion_nanguo);
//        EMOTION_STATIC_MAP.put("[酷]", R.drawable.emotion_ku);
//        EMOTION_STATIC_MAP.put("[冷汗]", R.drawable.emotion_lenghan);
//        EMOTION_STATIC_MAP.put("[抓狂]", R.drawable.emotion_zhuakuang);
//        EMOTION_STATIC_MAP.put("[吐]", R.drawable.emotion_tu);
//        EMOTION_STATIC_MAP.put("[偷笑]", R.drawable.emotion_touxiao);
//        EMOTION_STATIC_MAP.put("[可爱]", R.drawable.emotion_keai);
//        EMOTION_STATIC_MAP.put("[白眼]", R.drawable.emotion_baiyan);
//        EMOTION_STATIC_MAP.put("[傲慢]", R.drawable.emotion_aoman);
//        EMOTION_STATIC_MAP.put("[饥饿]", R.drawable.emotion_jie);
//        EMOTION_STATIC_MAP.put("[困]", R.drawable.emotion_kun);
//        EMOTION_STATIC_MAP.put("[惊恐]", R.drawable.emotion_jingkong);
//        EMOTION_STATIC_MAP.put("[流汗]", R.drawable.emotion_liuhan);
//        EMOTION_STATIC_MAP.put("[憨笑]", R.drawable.emotion_hanxiao);
//        EMOTION_STATIC_MAP.put("[大兵]", R.drawable.emotion_dabing);
//        EMOTION_STATIC_MAP.put("[奋斗]", R.drawable.emotion_fendou);
//        EMOTION_STATIC_MAP.put("[咒骂]", R.drawable.emotion_zouma);
//        EMOTION_STATIC_MAP.put("[疑问]", R.drawable.emotion_yiwen);
//        EMOTION_STATIC_MAP.put("[嘘]", R.drawable.emotion_xu);
//        EMOTION_STATIC_MAP.put("[晕]", R.drawable.emotion_yun);
//        EMOTION_STATIC_MAP.put("[折磨]", R.drawable.emotion_fakuang);
//        EMOTION_STATIC_MAP.put("[衰]", R.drawable.emotion_shuai);
//        EMOTION_STATIC_MAP.put("[骷髅]", R.drawable.emotion_kulou);
//        EMOTION_STATIC_MAP.put("[敲打]", R.drawable.emotion_qiaoda);
//        EMOTION_STATIC_MAP.put("[再见]", R.drawable.emotion_zaijian);
//        EMOTION_STATIC_MAP.put("[擦汗]", R.drawable.emotion_cahan);
//        EMOTION_STATIC_MAP.put("[抠鼻]", R.drawable.emotion_koubi);
//        EMOTION_STATIC_MAP.put("[鼓掌]", R.drawable.emotion_guzhang);
//        EMOTION_STATIC_MAP.put("[糗大了]", R.drawable.emotion_qiudale);
//        EMOTION_STATIC_MAP.put("[坏笑]", R.drawable.emotion_huaixiao);
//        EMOTION_STATIC_MAP.put("[左哼哼]", R.drawable.emotion_zuohengheng);
//        EMOTION_STATIC_MAP.put("[右哼哼]", R.drawable.emotion_youhengheng);
//        EMOTION_STATIC_MAP.put("[哈欠]", R.drawable.emotion_haqian);
//        EMOTION_STATIC_MAP.put("[鄙视]", R.drawable.emotion_bishi);
//        EMOTION_STATIC_MAP.put("[委屈]", R.drawable.emotion_weiqu);
//        EMOTION_STATIC_MAP.put("[快哭了]", R.drawable.emotion_kuaikule);
//        EMOTION_STATIC_MAP.put("[阴险]", R.drawable.emotion_yingxian);
//        EMOTION_STATIC_MAP.put("[亲亲]", R.drawable.emotion_qinqin);
//        EMOTION_STATIC_MAP.put("[吓]", R.drawable.emotion_xia);
//        EMOTION_STATIC_MAP.put("[可怜]", R.drawable.emotion_kelian);
//        EMOTION_STATIC_MAP.put("[菜刀]", R.drawable.emotion_caidao);
//        EMOTION_STATIC_MAP.put("[西瓜]", R.drawable.emotion_xigua);
//        EMOTION_STATIC_MAP.put("[啤酒]", R.drawable.emotion_pijiu);
//        EMOTION_STATIC_MAP.put("[篮球]", R.drawable.emotion_lanqiu);
//        EMOTION_STATIC_MAP.put("[乒乓]", R.drawable.emotion_pingpang);
//        EMOTION_STATIC_MAP.put("[咖啡]", R.drawable.emotion_kafei);
//        EMOTION_STATIC_MAP.put("[饭]", R.drawable.emotion_fan);
//        EMOTION_STATIC_MAP.put("[猪头]", R.drawable.emotion_zhutou);
//        EMOTION_STATIC_MAP.put("[玫瑰]", R.drawable.emotion_meigui);
//        EMOTION_STATIC_MAP.put("[凋谢]", R.drawable.emotion_diaoxie);
//        EMOTION_STATIC_MAP.put("[示爱]", R.drawable.emotion_shiai);
//        EMOTION_STATIC_MAP.put("[爱心]", R.drawable.emotion_aixin);
//        EMOTION_STATIC_MAP.put("[心碎]", R.drawable.emotion_xinsui);
//        EMOTION_STATIC_MAP.put("[蛋糕]", R.drawable.emotion_dangao);
//        EMOTION_STATIC_MAP.put("[闪电]", R.drawable.emotion_shandian);
//        EMOTION_STATIC_MAP.put("[炸弹]", R.drawable.emotion_zhadan);
//        EMOTION_STATIC_MAP.put("[刀]", R.drawable.emotion_dao);
//        EMOTION_STATIC_MAP.put("[足球]", R.drawable.emotion_zhuqiu);
//        EMOTION_STATIC_MAP.put("[瓢虫]", R.drawable.emotion_pachong);
//        EMOTION_STATIC_MAP.put("[便便]", R.drawable.emotion_bianbian);
//        EMOTION_STATIC_MAP.put("[月亮]", R.drawable.emotion_yueliang);
//        EMOTION_STATIC_MAP.put("[太阳]", R.drawable.emotion_taiyang);
//        EMOTION_STATIC_MAP.put("[礼物]", R.drawable.emotion_liwu);
//        EMOTION_STATIC_MAP.put("[拥抱]", R.drawable.emotion_baobao);
//        EMOTION_STATIC_MAP.put("[强]", R.drawable.emotion_qiang);
//        EMOTION_STATIC_MAP.put("[弱]", R.drawable.emotion_ruo);
//        EMOTION_STATIC_MAP.put("[握手]", R.drawable.emotion_woshou);
//        EMOTION_STATIC_MAP.put("[胜利]", R.drawable.emotion_shengli);
//        EMOTION_STATIC_MAP.put("[抱拳]", R.drawable.emotion_baoquan);
//        EMOTION_STATIC_MAP.put("[勾引]", R.drawable.emotion_gouying);
//        EMOTION_STATIC_MAP.put("[拳头]", R.drawable.emotion_quantou);
//        EMOTION_STATIC_MAP.put("[差劲]", R.drawable.emotion_chajing);
//        EMOTION_STATIC_MAP.put("[爱你]", R.drawable.emotion_aini);
//        EMOTION_STATIC_MAP.put("[NO]", R.drawable.emotion_no);
//        EMOTION_STATIC_MAP.put("[OK]", R.drawable.emotion_ok);
//        EMOTION_STATIC_MAP.put("[爱情]", R.drawable.emotion_aiqing);
//        EMOTION_STATIC_MAP.put("[飞吻]", R.drawable.emotion_feiwen);
//        EMOTION_STATIC_MAP.put("[跳跳]", R.drawable.emotion_tiaotiao);
//        EMOTION_STATIC_MAP.put("[发抖]", R.drawable.emotion_fadou);
//        EMOTION_STATIC_MAP.put("[怄火]", R.drawable.emotion_ouhuo);
//        EMOTION_STATIC_MAP.put("[转圈]", R.drawable.emotion_zhuanquan);
//        EMOTION_STATIC_MAP.put("[磕头]", R.drawable.emotion_ketou);
//        EMOTION_STATIC_MAP.put("[回头]", R.drawable.emotion_huitou);
//        EMOTION_STATIC_MAP.put("[跳绳]", R.drawable.emotion_tiaosheng);
//        EMOTION_STATIC_MAP.put("[挥手]", R.drawable.emotion_huishou);
//        EMOTION_STATIC_MAP.put("[激动]", R.drawable.emotion_jidong);
//        EMOTION_STATIC_MAP.put("[街舞]", R.drawable.emotion_jiewu);
//        EMOTION_STATIC_MAP.put("[献吻]", R.drawable.emotion_xianwen);
//        EMOTION_STATIC_MAP.put("[左太极]", R.drawable.emotion_zuotaiji);
//        EMOTION_STATIC_MAP.put("[右太极]", R.drawable.emotion_youtaiji);
//        EMOTION_STATIC_MAP.put("[双喜]", R.drawable.emotion_shuangxi);
//        EMOTION_STATIC_MAP.put("[鞭炮]", R.drawable.emotion_bianpao);
//        EMOTION_STATIC_MAP.put("[灯笼]", R.drawable.emotion_denglong);
//        EMOTION_STATIC_MAP.put("[发财]", R.drawable.emotion_facai);
//        EMOTION_STATIC_MAP.put("[K歌]", R.drawable.emotion_kge);
//        EMOTION_STATIC_MAP.put("[购物]", R.drawable.emotion_gouwu);
//        EMOTION_STATIC_MAP.put("[邮件]", R.drawable.emotion_youjian);
//        EMOTION_STATIC_MAP.put("[帅]", R.drawable.emotion_dashuai);
//        EMOTION_STATIC_MAP.put("[喝彩]", R.drawable.emotion_hecai);
//        EMOTION_STATIC_MAP.put("[祈祷]", R.drawable.emotion_qidao);
//        EMOTION_STATIC_MAP.put("[爆筋]", R.drawable.emotion_baojing);
//        EMOTION_STATIC_MAP.put("[棒棒糖]", R.drawable.emotion_bangbangtang);
//        EMOTION_STATIC_MAP.put("[喝奶]", R.drawable.emotion_henai);
//        EMOTION_STATIC_MAP.put("[下面]", R.drawable.emotion_xiamian);
//        EMOTION_STATIC_MAP.put("[香蕉]", R.drawable.emotion_xiangjiao);
//        EMOTION_STATIC_MAP.put("[飞机]", R.drawable.emotion_feiji);
//        EMOTION_STATIC_MAP.put("[开车]", R.drawable.emotion_kaiche);
//        EMOTION_STATIC_MAP.put("[左车头]", R.drawable.emotion_zuochetou);
//        EMOTION_STATIC_MAP.put("[车厢]", R.drawable.emotion_chexiang);
//        EMOTION_STATIC_MAP.put("[右车头]", R.drawable.emotion_youchexiang);
//        EMOTION_STATIC_MAP.put("[多云]", R.drawable.emotion_duoyun);
//        EMOTION_STATIC_MAP.put("[下雨]", R.drawable.emotion_xiayu);
//        EMOTION_STATIC_MAP.put("[钞票]", R.drawable.emotion_chaopiao);
//        EMOTION_STATIC_MAP.put("[熊猫]", R.drawable.emotion_xiongmao);
//        EMOTION_STATIC_MAP.put("[灯泡]", R.drawable.emotion_dengpao);
//        EMOTION_STATIC_MAP.put("[风车]", R.drawable.emotion_fengche);
//        EMOTION_STATIC_MAP.put("[闹钟]", R.drawable.emotion_naozhong);
//        EMOTION_STATIC_MAP.put("[打伞]", R.drawable.emotion_dashan);
//        EMOTION_STATIC_MAP.put("[彩球]", R.drawable.emotion_caiqiu);
//        EMOTION_STATIC_MAP.put("[钻戒]", R.drawable.emotion_zhuanjie);
//        EMOTION_STATIC_MAP.put("[沙发]", R.drawable.emotion_shafa);
//        EMOTION_STATIC_MAP.put("[纸巾]", R.drawable.emotion_zhijing);
//        EMOTION_STATIC_MAP.put("[药]", R.drawable.emotion_yao);
//        EMOTION_STATIC_MAP.put("[手枪]", R.drawable.emotion_shouqiang);
//        EMOTION_STATIC_MAP.put("[青蛙]", R.drawable.emotion_qingwa);
    }
}
