package com.mding.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mding.dao.GroupUserRelation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_USER_RELATION".
*/
public class GroupUserRelationDao extends AbstractDao<GroupUserRelation, Long> {

    public static final String TABLENAME = "GROUP_USER_RELATION";

    /**
     * Properties of entity GroupUserRelation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property GroupId = new Property(2, String.class, "groupId", false, "GROUP_ID");
        public final static Property FriendId = new Property(3, String.class, "friendId", false, "FRIEND_ID");
        public final static Property CarteName = new Property(4, String.class, "carteName", false, "CARTE_NAME");
        public final static Property IdentitType = new Property(5, String.class, "identitType", false, "IDENTIT_TYPE");
        public final static Property OperationType = new Property(6, String.class, "operationType", false, "OPERATION_TYPE");
        public final static Property Bannedtype = new Property(7, String.class, "bannedtype", false, "BANNEDTYPE");
        public final static Property GroupManageId = new Property(8, String.class, "groupManageId", false, "GROUP_MANAGE_ID");
        public final static Property DisturbType = new Property(9, String.class, "disturbType", false, "DISTURB_TYPE");
        public final static Property AssistantType = new Property(10, String.class, "assistantType", false, "ASSISTANT_TYPE");
        public final static Property TopType = new Property(11, String.class, "topType", false, "TOP_TYPE");
        public final static Property Created = new Property(12, String.class, "created", false, "CREATED");
        public final static Property Modified = new Property(13, String.class, "modified", false, "MODIFIED");
        public final static Property RecordTime = new Property(14, String.class, "recordTime", false, "RECORD_TIME");
    }


    public GroupUserRelationDao(DaoConfig config) {
        super(config);
    }
    
    public GroupUserRelationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_USER_RELATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"GROUP_ID\" TEXT," + // 2: groupId
                "\"FRIEND_ID\" TEXT," + // 3: friendId
                "\"CARTE_NAME\" TEXT," + // 4: carteName
                "\"IDENTIT_TYPE\" TEXT," + // 5: identitType
                "\"OPERATION_TYPE\" TEXT," + // 6: operationType
                "\"BANNEDTYPE\" TEXT," + // 7: bannedtype
                "\"GROUP_MANAGE_ID\" TEXT," + // 8: groupManageId
                "\"DISTURB_TYPE\" TEXT," + // 9: disturbType
                "\"ASSISTANT_TYPE\" TEXT," + // 10: assistantType
                "\"TOP_TYPE\" TEXT," + // 11: topType
                "\"CREATED\" TEXT," + // 12: created
                "\"MODIFIED\" TEXT," + // 13: modified
                "\"RECORD_TIME\" TEXT);"); // 14: recordTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_GROUP_USER_RELATION_USER_ID_DESC_GROUP_ID_DESC ON \"GROUP_USER_RELATION\"" +
                " (\"USER_ID\" DESC,\"GROUP_ID\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_USER_RELATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupUserRelation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String groupId = entity.getGroupId();
        if (groupId != null) {
            stmt.bindString(3, groupId);
        }
 
        String friendId = entity.getFriendId();
        if (friendId != null) {
            stmt.bindString(4, friendId);
        }
 
        String carteName = entity.getCarteName();
        if (carteName != null) {
            stmt.bindString(5, carteName);
        }
 
        String identitType = entity.getIdentitType();
        if (identitType != null) {
            stmt.bindString(6, identitType);
        }
 
        String operationType = entity.getOperationType();
        if (operationType != null) {
            stmt.bindString(7, operationType);
        }
 
        String bannedtype = entity.getBannedtype();
        if (bannedtype != null) {
            stmt.bindString(8, bannedtype);
        }
 
        String groupManageId = entity.getGroupManageId();
        if (groupManageId != null) {
            stmt.bindString(9, groupManageId);
        }
 
        String disturbType = entity.getDisturbType();
        if (disturbType != null) {
            stmt.bindString(10, disturbType);
        }
 
        String assistantType = entity.getAssistantType();
        if (assistantType != null) {
            stmt.bindString(11, assistantType);
        }
 
        String topType = entity.getTopType();
        if (topType != null) {
            stmt.bindString(12, topType);
        }
 
        String created = entity.getCreated();
        if (created != null) {
            stmt.bindString(13, created);
        }
 
        String modified = entity.getModified();
        if (modified != null) {
            stmt.bindString(14, modified);
        }
 
        String recordTime = entity.getRecordTime();
        if (recordTime != null) {
            stmt.bindString(15, recordTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupUserRelation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String groupId = entity.getGroupId();
        if (groupId != null) {
            stmt.bindString(3, groupId);
        }
 
        String friendId = entity.getFriendId();
        if (friendId != null) {
            stmt.bindString(4, friendId);
        }
 
        String carteName = entity.getCarteName();
        if (carteName != null) {
            stmt.bindString(5, carteName);
        }
 
        String identitType = entity.getIdentitType();
        if (identitType != null) {
            stmt.bindString(6, identitType);
        }
 
        String operationType = entity.getOperationType();
        if (operationType != null) {
            stmt.bindString(7, operationType);
        }
 
        String bannedtype = entity.getBannedtype();
        if (bannedtype != null) {
            stmt.bindString(8, bannedtype);
        }
 
        String groupManageId = entity.getGroupManageId();
        if (groupManageId != null) {
            stmt.bindString(9, groupManageId);
        }
 
        String disturbType = entity.getDisturbType();
        if (disturbType != null) {
            stmt.bindString(10, disturbType);
        }
 
        String assistantType = entity.getAssistantType();
        if (assistantType != null) {
            stmt.bindString(11, assistantType);
        }
 
        String topType = entity.getTopType();
        if (topType != null) {
            stmt.bindString(12, topType);
        }
 
        String created = entity.getCreated();
        if (created != null) {
            stmt.bindString(13, created);
        }
 
        String modified = entity.getModified();
        if (modified != null) {
            stmt.bindString(14, modified);
        }
 
        String recordTime = entity.getRecordTime();
        if (recordTime != null) {
            stmt.bindString(15, recordTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupUserRelation readEntity(Cursor cursor, int offset) {
        GroupUserRelation entity = new GroupUserRelation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // groupId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // friendId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // carteName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // identitType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // operationType
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bannedtype
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // groupManageId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // disturbType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // assistantType
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // topType
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // created
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // modified
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // recordTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupUserRelation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGroupId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFriendId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCarteName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIdentitType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOperationType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBannedtype(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setGroupManageId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDisturbType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAssistantType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTopType(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCreated(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setModified(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setRecordTime(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupUserRelation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupUserRelation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupUserRelation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
